USE [master]
GO

/****** Object:  Database [BookWorm]    Script Date: 11/18/2019 9:34:13 AM ******/
CREATE DATABASE [BookWorm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookWorm', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BookWorm.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookWorm_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BookWorm_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BookWorm] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookWorm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookWorm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookWorm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookWorm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookWorm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookWorm] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookWorm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookWorm] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BookWorm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookWorm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookWorm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookWorm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookWorm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookWorm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookWorm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookWorm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookWorm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookWorm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookWorm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookWorm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookWorm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookWorm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookWorm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookWorm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookWorm] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BookWorm] SET  MULTI_USER 
GO

ALTER DATABASE [BookWorm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookWorm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookWorm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookWorm] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BookWorm] SET  READ_WRITE 
GO


